name: Update BAK on Rejected Translation PR

on:
  pull_request:
    types: [closed]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    outputs:
      has_label: ${{ steps.check-labels-step.outputs.has_label }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Check jq Version
        run: |
          jq --version

      - name: Debug Event
        run: |
          echo "Event: ${{ toJson(github.event) }}"

      - name: Debug Labels
        run: |
          echo "Labels: ${{ toJson(github.event.pull_request.labels) }}"

      - name: Check Labels
        id: check-labels-step
        run: |
          LABELS=$(echo ${{ toJson(github.event.pull_request.labels) }} | jq -r '.[] | .name')
          echo "Labels: $LABELS"
          if echo "$LABELS" | grep -qw 'automated-translation'; then
            echo "has_label=true" >> $GITHUB_OUTPUT
          else
            echo "has_label=false" >> $GITHUB_OUTPUT
          fi

  update-bak-on-rejection:
    needs: check-labels
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.merged && needs.check-labels.outputs.has_label == 'true' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Update BAK File
        run: |
          cp src/main/resources/messages_en.properties src/main/resources/messages_en.properties.bak
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add src/main/resources/messages_en.properties.bak
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update BAK file after rejected translation PR #${{ github.event.pull_request.number }}"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}