name: Verify Workflow Trigger on PR Closure

on:
  pull_request:
    types: [closed]

jobs:
  verify-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm Workflow Execution
        run: echo "Workflow triggered on PR closure."