name: Update BAK on Rejected Translation PR

on:
  pull_request:
    types: [closed]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    outputs:
      has_label: ${{ steps.check-labels-step.outputs.has_label }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: jakejarvis/install-jq-action@v1

      - name: Check Labels
        id: check-labels-step
        run: |
          LABELS=$(echo ${{ github.event.pull_request.labels }} | jq -r '.[] | .name')
          echo "Labels: $LABELS"
          if echo "$LABELS" | grep -qw 'automated-translation'; then
            echo "has_label=true" >> $GITHUB_OUTPUT
          else
            echo "has_label=false" >> $GITHUB_OUTPUT
          fi

  update-bak-on-rejection:
    needs: check-labels
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.merged && needs.check-labels.outputs.has_label == 'true' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update BAK File
        run: |
          cp src/main/resources/messages_en.properties src/main/resources/messages_en.properties.bak
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add src/main/resources/messages_en.properties.bak
          git commit -m "Update BAK file after rejected translation PR #${{ github.event.pull_request.number }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}