name: Update BAK on Rejected Translation PR

on:
  pull_request:
    types: [closed]

jobs:
  update-bak-on-rejection:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == false && github.event.pull_request.labels.*.name contains 'automated-translation' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update BAK File
        run: |
          cp src/main/resources/messages_en.properties src/main/resources/messages_en.properties.bak
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add src/main/resources/messages_en.properties.bak
          git commit -m "Update BAK file after rejected translation PR #${{ github.event.pull_request.number }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}